# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [2]:
import pandas as pd

In [ ]:
jobs = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user",
    sep="|",
    names=["age", "gender", "job", "ID"],
)

print(jobs.head())
print("\n")
print(jobs.tail())
print("\n")
print(jobs.dtypes)

   age gender         job     ID
1   24      M  technician  85711
2   53      F       other  94043
3   23      M      writer  32067
4   24      M  technician  43537
5   33      F       other  15213


     age gender            job     ID
939   26      F        student  33319
940   32      M  administrator  02215
941   20      M        student  97229
942   48      F      librarian  78209
943   22      M        student  77841


age       int64
gender      str
job         str
ID          str
dtype: object

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [ ]:
alcohol = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv",
    sep=",",
)

alcohol.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [7]:
alcohol_index = alcohol.set_index("country")

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [14]:
alcohol_index.loc["Zimbabwe"]

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [16]:
alcohol_index.loc["Zimbabwe", "continent"]

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [ ]:
link = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv"

In [23]:
ufo_1 = pd.read_csv(
    link,
    sep=",",
    header=0, 
    names=["ville", "couleur", "forme", "etat", "datetime"]
)

print(ufo_1)

                      ville couleur     forme etat          datetime
0                    Ithaca     NaN  TRIANGLE   NY    6/1/1930 22:00
1               Willingboro     NaN     OTHER   NJ   6/30/1930 20:00
2                   Holyoke     NaN      OVAL   CO   2/15/1931 14:00
3                   Abilene     NaN      DISK   KS    6/1/1931 13:00
4      New York Worlds Fair     NaN     LIGHT   NY   4/18/1933 19:00
...                     ...     ...       ...  ...               ...
18236            Grant Park     NaN  TRIANGLE   IL  12/31/2000 23:00
18237           Spirit Lake     NaN      DISK   IA  12/31/2000 23:00
18238           Eagle River     NaN       NaN   WI  12/31/2000 23:45
18239           Eagle River     RED     LIGHT   WI  12/31/2000 23:45
18240                  Ybor     NaN      OVAL   FL  12/31/2000 23:59

[18241 rows x 5 columns]

In [24]:
ufo_2 = pd.read_csv(
    link,
    sep=",",
)

print(
    ufo_2.rename(
        {
            "City": "ville",
            "Colors Reported": "couleur",
            "Shape Reported": "forme",
            "State": "etat",
            "Time": "datetime",
        },
        axis=1,
    )
)

                      ville couleur     forme etat          datetime
0                    Ithaca     NaN  TRIANGLE   NY    6/1/1930 22:00
1               Willingboro     NaN     OTHER   NJ   6/30/1930 20:00
2                   Holyoke     NaN      OVAL   CO   2/15/1931 14:00
3                   Abilene     NaN      DISK   KS    6/1/1931 13:00
4      New York Worlds Fair     NaN     LIGHT   NY   4/18/1933 19:00
...                     ...     ...       ...  ...               ...
18236            Grant Park     NaN  TRIANGLE   IL  12/31/2000 23:00
18237           Spirit Lake     NaN      DISK   IA  12/31/2000 23:00
18238           Eagle River     NaN       NaN   WI  12/31/2000 23:45
18239           Eagle River     RED     LIGHT   WI  12/31/2000 23:45
18240                  Ybor     NaN      OVAL   FL  12/31/2000 23:59

[18241 rows x 5 columns]

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [29]:
ufo_1.iloc[:3, :]

         ville couleur     forme etat         datetime
0       Ithaca     NaN  TRIANGLE   NY   6/1/1930 22:00
1  Willingboro     NaN     OTHER   NJ  6/30/1930 20:00
2      Holyoke     NaN      OVAL   CO  2/15/1931 14:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [30]:
ufo_1.loc[ufo_1.index < 3]

         ville couleur     forme etat         datetime
0       Ithaca     NaN  TRIANGLE   NY   6/1/1930 22:00
1  Willingboro     NaN     OTHER   NJ  6/30/1930 20:00
2      Holyoke     NaN      OVAL   CO  2/15/1931 14:00