# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [5]:
import pandas as pd

In [7]:
fruit = pd.DataFrame([[30, 21]], columns=["Apples", "Bananas"])

fruit

   Apples  Bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [10]:
fruit_vendors = pd.DataFrame(
    {"Apples": [35, 21], "Bananas": [41, 34]},
    index=["2017 Sales", "2018 Sales"]
)

fruit_vendors

            Apples  Bananas
2017 Sales      35       41
2018 Sales      21       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [23]:
for col in fruit_vendors:
    print(f"{fruit_vendors[col]}\n")

2017 Sales    35
2018 Sales    21
Name: Apples, dtype: int64

2017 Sales    41
2018 Sales    34
Name: Bananas, dtype: int64

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [37]:
fruit_vendors.drop("2017 Sales") # Par défaut, axis=0
# On peut aussi utiliser 
# fruit_vendors.drop(index="2017 Sales")

            Apples  Bananas
2018 Sales      21       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [36]:
fruit_vendors.drop("Apples", axis=1)
# On peut aussi utiliser 
# fruit_vendors.drop(columns="Apples")

            Bananas
2017 Sales       41
2018 Sales       34