In [1]:
import pandas as pd

### Welcome to the Apply Challenge

In [4]:
link = 'https://raw.githubusercontent.com/chriszapp/datasets/main/books.csv'
books = pd.read_csv(link, nrows = 13)

In [7]:
# Firstly, have a look at the dataset
display(books.head())

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [8]:
print(books.shape)

(13, 12)

In [9]:
# Mission 1: use apply to create a new column called 'reviews_opinion': if the ratings is between 4.5 and 5, the reviews_opinion is 'very good';
# if the rating is between 4 and 4.5, the reviews_opinion is 'good'; if the rating is between 3 and 4, the reviews_opinions will be 'neutral';
# if the rating is up to 3 the reviews_opinion is going to be 'bad'

# Add your code here
def reviews_opinion_apply(row):
    if row['average_rating'] < 3:
        return 'bad'
    elif 3 <= row['average_rating'] < 4:
        return 'neutral'
    elif 4 <= row['average_rating'] < 4.5:
        return 'good'
    else:
        return 'very good'

books['reviews_opinion'] = books.apply(reviews_opinion_apply, axis = 1)
books.loc[0:5, ['average_rating', 'reviews_opinion']]

   average_rating reviews_opinion
0            4.57       very good
1            4.49            good
2            4.42            good
3            4.56       very good
4            4.78       very good
5            3.74         neutral

In [14]:
# Mission 2: using apply with a function, create a column with the number of authors per book
# (note that in the column 'authors', each name of the author is divided with the character '/')

# Add your code here
def nb_authors(authors):
    return len(authors.split(sep = '/'))

books['number_authors'] = books.authors.apply(nb_authors)
books.loc[0:5, ['authors', 'number_authors']]

                      authors  number_authors
0  J.K. Rowling/Mary GrandPré               2
1  J.K. Rowling/Mary GrandPré               2
2                J.K. Rowling               1
3  J.K. Rowling/Mary GrandPré               2
4  J.K. Rowling/Mary GrandPré               2
5      W. Frederick Zimmerman               1

In [15]:
# Mission 3: rewrite the same task as Mission 2 using the lamdba function

# Add your code here
books['number_authors'] = books.authors.apply(lambda x: len(x.split(sep = '/')))
books.loc[0:5, ['authors', 'number_authors']]

                      authors  number_authors
0  J.K. Rowling/Mary GrandPré               2
1  J.K. Rowling/Mary GrandPré               2
2                J.K. Rowling               1
3  J.K. Rowling/Mary GrandPré               2
4  J.K. Rowling/Mary GrandPré               2
5      W. Frederick Zimmerman               1

In [19]:
# Mission 4: create a column 'comment_ration'.
# Use the columns 'ratings_count' and 'text_reviews_count' to calculate the percentage of how many text review per reviews are per book:
# percentage = text / reviews * 100
# Use the mathematical operations between columns

# Add your code here
books["reviews_percentage"] = round((books['text_reviews_count'] / books['ratings_count']) * 100, 2)

books[['ratings_count', 'text_reviews_count', 'reviews_percentage']]

    ratings_count  text_reviews_count  reviews_percentage
0         2095690               27591                1.32
1         2153167               29221                1.36
2            6333                 244                3.85
3         2339585               36325                1.55
4           41428                 164                0.40
5              19                   1                5.26
6           28242                 808                2.86
7            3628                 254                7.00
8          249558                4080                1.63
9            4930                 460                9.33
10           1266                 253               19.98
11           2877                 195                6.78
12         248558                9396                3.78

In [23]:
# Mission 5: obtain the same result of Mission 4 using apply with a function.
# Try both methods to apply to the whole dataset and apply to selected columns

# Add your code here
def text_per_reviews(row):
    return round((row['text_reviews_count'] / row['ratings_count']) * 100, 2)

books["reviews_percentage"] = books.apply(text_per_reviews, axis = 1)

books[['ratings_count', 'text_reviews_count', 'reviews_percentage']]

    ratings_count  text_reviews_count  reviews_percentage
0         2095690               27591                1.32
1         2153167               29221                1.36
2            6333                 244                3.85
3         2339585               36325                1.55
4           41428                 164                0.40
5              19                   1                5.26
6           28242                 808                2.86
7            3628                 254                7.00
8          249558                4080                1.63
9            4930                 460                9.33
10           1266                 253               19.98
11           2877                 195                6.78
12         248558                9396                3.78

In [22]:
def text_per_reviews(row):
    return round((row.iloc[1] / row.iloc[0]) * 100, 2)

books["reviews_percentage"] = books[['ratings_count', 'text_reviews_count']].apply(text_per_reviews, axis = 1)

books[['ratings_count', 'text_reviews_count', 'reviews_percentage']]

    ratings_count  text_reviews_count  reviews_percentage
0         2095690               27591                1.32
1         2153167               29221                1.36
2            6333                 244                3.85
3         2339585               36325                1.55
4           41428                 164                0.40
5              19                   1                5.26
6           28242                 808                2.86
7            3628                 254                7.00
8          249558                4080                1.63
9            4930                 460                9.33
10           1266                 253               19.98
11           2877                 195                6.78
12         248558                9396                3.78

In [24]:
# Mission 6: obtain the same result of Mission 5 using apply lambda
# Try both methods to apply to the whole dataset and apply to selected columns

# Add your code here
books["reviews_percentage"] = books.apply(
    lambda x: round((x['text_reviews_count'] / x['ratings_count']) * 100, 2),
    axis = 1)

books[['ratings_count', 'text_reviews_count', 'reviews_percentage']]

    ratings_count  text_reviews_count  reviews_percentage
0         2095690               27591                1.32
1         2153167               29221                1.36
2            6333                 244                3.85
3         2339585               36325                1.55
4           41428                 164                0.40
5              19                   1                5.26
6           28242                 808                2.86
7            3628                 254                7.00
8          249558                4080                1.63
9            4930                 460                9.33
10           1266                 253               19.98
11           2877                 195                6.78
12         248558                9396                3.78

In [25]:
books["reviews_percentage"] = books[['ratings_count', 'text_reviews_count']].apply(
    lambda row: round((row.iloc[1] / row.iloc[0]) * 100, 2),
    axis = 1)

books[['ratings_count', 'text_reviews_count', 'reviews_percentage']]

    ratings_count  text_reviews_count  reviews_percentage
0         2095690               27591                1.32
1         2153167               29221                1.36
2            6333                 244                3.85
3         2339585               36325                1.55
4           41428                 164                0.40
5              19                   1                5.26
6           28242                 808                2.86
7            3628                 254                7.00
8          249558                4080                1.63
9            4930                 460                9.33
10           1266                 253               19.98
11           2877                 195                6.78
12         248558                9396                3.78

In [31]:
from datetime import datetime

In [35]:
books.publication_date

0     9/16/2006
1      9/1/2004
2     11/1/2003
3      5/1/2004
4     9/13/2004
5     4/26/2005
6     9/12/2005
7     11/1/2005
8     4/30/2002
9      8/3/2004
10    3/23/2005
11    1/17/1996
12    9/14/2004
Name: publication_date, dtype: str

In [44]:
# Mission 7: extract the year from the publication_date column. How many years of publications are recorded in this dataset? Which are them?
# Add your code here
books["publication_year"] = books.publication_date.map(lambda x: int(x[-4:]))
books.publication_year.sort_values().unique()

array([1996, 2002, 2003, 2004, 2005, 2006])

In [45]:
# Méthode avec datetime :
books["publication_year_dt"] = books.publication_date.map(lambda x: datetime.strftime(datetime.strptime(x, "%m/%d/%Y"), "%Y"))
books.publication_year_dt.sort_values().unique()

<StringArray>
['1996', '2002', '2003', '2004', '2005', '2006']
Length: 6, dtype: str